       </td>
      </tr></tbody></table>
     </font></center>
    </div>
   </td>
  </tr><tr>
  <td colSpan=5 height=20 width="805" background="llblue.jpg" style="background-repeat: repeat-y;">
   <p align=left><font face="Verdana" size="1"><a href="http://www.aevandevliet.be">
    Copyright</a> © 1995-2014 <a href="http://www.aevandevliet.be">AE Van de Vliet bvba</a> 
    All rights reserved.</font></p>
  </td>
 </tr></tbody></table>
</div></body>
</html>
